# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/debian9"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../source", "/home/vagrant/source"

  config.vm.provider :virtualbox do |v|
    #debug v.gui = true
    v.name = "atc.dev"
    v.memory = 8192
    v.cpus = 2
    #v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end



  # config.vm.network "forwarded_port", guest: 80, host: 8000
  # config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.provision "ansible_local" do |ansible|
    ansible.version = "latest"
    ansible.install_mode = "pip"
  # ansible.version = "2.2.1.0"
    ansible.playbook = "ansible/main.yml"
  end
end
